# coding: utf-8
config:
    sitename: Iguana
    etsy:
        key: "jzs8sdrx6a9c4qepmox2zjh0"
        secret: "uvy09ldman"
    domain: www.iguana.com
    session_secret: zanzibar_499_devils
    tabs:
        price_comparisions:
            title: P
            description: ""
        linked_data:
            title: Technology
            description: |
              We use <b>Linked Data</b> to promote data open-ness and ease-of-access and extensibility. Furthermore we are interested
              in seeing mashups of pricing data with other datasets to detect other kinds of correlations.