# coding: utf-8
config:
    sitename: Iguana
    etsy:
        key: "jzs8sdrx6a9c4qepmox2zjh0"
        secret: "uvy09ldman"
    domain: www.iguana.com
    session_secret: zanzibar_499_devils
    tabs:
        special_tab:
            title: "Special Tab"
            description: "My special tab"
        price_comparisions:
            title: Prices
            description: "Compare prices for different product categories to improve your sales and price alignment."
        linked_data:
            title: Technology
            description: |
              We use <b>Linked Data</b> to promote data open-ness and ease-of-access and extensibility. Furthermore we are interested
              in seeing mashups of pricing data with other datasets to detect other kinds of correlations.